### ISSUE TITLE
Add options to Autocomplete

### ISSUE THREAD

**Issue by sardoj** [dericcain/google-address-autocomplete#13]
Hello,

Thank you for your tool.
Is it possible to make possible to add options to Autocomplete? For example I would like to restrict the area to a country. The code is the following:

```javascript
 this.autocomplete = new google.maps.places.Autocomplete(this.element, {
    types: ["geocode"],
    componentRestrictions: {country: "fr"} // This option to restrict to France
}), this.autocomplete.addListener("place_changed", this.extractAddress)
```

Can you add the possibility to add options, for example like this:
```javascript
var options= {
 componentRestrictions: {country: "fr"}
}
new AddressAutocomplete("#address-search", options, results => {...})
```

It will be necessary to merge with default option `types: ["geocode"]`

Thanks for your help!

**Comment by dericcain** [comment]
@sardoj I really like that idea. Would you mind make a PR and adding that feature? I could help you along the way (if needed). If this is implemented, then it would need to be a `v2` feature because it would break current compatibility. Let me know your thoughts on this.

**Comment by sardoj** [comment]
@dericgw Ok I do that

**Comment by dericcain** [comment]
#14 closes this.

**Comment by sardoj** [comment]
Thanks for merging!
Please could you also update the version on npm?

**Comment by dericcain** [comment]
@sardoj It should be published now.
