### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by ovflowd** [dericcain/google-address-autocomplete#15]
After giving a look in the source code, I see that there is being used the  `readyStateChange` (https://github.com/dericgw/google-address-autocomplete/blob/master/src/index.js#L65) event. But this one only is fired within Internet Explorer and Microsoft Edge.

So on Chrome and Firefox this library would not be working...

I suggest a change to check if the document finished to load. Instead of this one.

**Comment by ovflowd** [comment]
![image](https://user-images.githubusercontent.com/12037269/53136646-6b01f880-355e-11e9-99a4-33c042923b04.png)

You may see that the `focus` event is not being fired up (https://github.com/dericgw/google-address-autocomplete/blob/master/src/index.js#L67)

**Comment by dericcain** [comment]
@ovflowd Are you experiencing some specific issue? The package has been working and I just tested in Chrome and it is working fine. 

Also, the `focus` event tells the browser to request location access and it is working as well (tested this too):
![image](https://cl.ly/0108dc/Screen%252520Recording%2525202019-02-20%252520at%25252009.56%252520PM.gif)

If there is a specific issue that you need help with, let me know. For now, I am going to close this issue. If you do have a specific issue, I will open it back up or feel free to open another issue.
