### ISSUE TITLE
Update documentation to show that multiple instances can be created

### ISSUE THREAD

**Issue by ghost** [dericcain/google-address-autocomplete#3]
If you look at #1 you will see that this library now has the ability to handle multiple instances of the autocomplete. Essentially, you can do this:

```JavaScript
new AddressAutocomplete('.shipping-address', result => console.log(result));
new AddressAutocomplete('.billing-address', result => console.log(result));
```
And it will work just fine. The docs need to be updated to show that this can be accomplished.

**Comment by tejazz** [comment]
I would like to take this up.

**Comment by ghost** [comment]
@Tarique102 Have at it! Let me know if you need assistance.
