### ISSUE TITLE
Broken link in documentation (super easy fix)

### ISSUE THREAD

**Issue by ghost** [dericcain/google-address-autocomplete#4]
If you look at the contributing link at the bottom of the readme, the link is broken because it has `.ms` instead of `.md` as an extension. You should just be able to change the one letter from `s` to `d` to fix it.

**Comment by tejazz** [comment]
I am already changing the documentation. This should be done as well.

**Comment by ghost** [comment]
Perfect!

Deric Cain
@dericcain
https://dericcain.com
