### ISSUE TITLE
Pass additional data to response

### ISSUE THREAD

**Issue by Braunson** [dericcain/google-address-autocomplete#8]
It would be nice to access other data in the response such as 

- geometry 
    - latitude
    - longitude
- id
- place_id
- url
- vicinity
- utc_offset
- address_components > neightbourhood

**Comment by dericcain** [comment]
I love that idea! Would you be willing to submit a PR? I could help you along the way if needed.

**Comment by Braunson** [comment]
Sure I'll give it a go

**Comment by Braunson** [comment]
@dericgw I'm following the CONTRIBUTING.md file but get this error on the 3rd step. (with no code changed)

```
~\Documents\GitHub\google-address-autocomplete [master ≡ +0 ~4 -0 !]> npm run build

> google-address-autocomplete@1.2.0 build C:\Users\Braunson\Documents\GitHub\google-address-autocomplete
> ./node_modules/rollup/bin/rollup --config rollup.config.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! google-address-autocomplete@1.2.0 build: `./node_modules/rollup/bin/rollup --config rollup.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the google-address-autocomplete@1.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Braunson\AppData\Roaming\npm-cache\_logs\2017-12-12T15_12_12_864Z-debug.log
```

This is the debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v7.5.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle google-address-autocomplete@1.2.0~prebuild: google-address-autocomplete@1.2.0
6 info lifecycle google-address-autocomplete@1.2.0~build: google-address-autocomplete@1.2.0
7 verbose lifecycle google-address-autocomplete@1.2.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle google-address-autocomplete@1.2.0~build: PATH: F:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin
9 verbose lifecycle google-address-autocomplete@1.2.0~build: CWD: C:\Users\Braunson\Documents\GitHub\google-address-autocomplete
10 silly lifecycle google-address-autocomplete@1.2.0~build: Args: [ '/d /s /c',
10 silly lifecycle   './node_modules/rollup/bin/rollup --config rollup.config.js' ]
11 silly lifecycle google-address-autocomplete@1.2.0~build: Returned: code: 1  signal: null
12 info lifecycle google-address-autocomplete@1.2.0~build: Failed to exec build script
13 verbose stack Error: google-address-autocomplete@1.2.0 build: `./node_modules/rollup/bin/rollup --config rollup.config.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (F:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at EventEmitter.emit (events.js:192:7)
13 verbose stack     at ChildProcess.<anonymous> (F:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:192:7)
13 verbose stack     at maybeClose (internal/child_process.js:890:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid google-address-autocomplete@1.2.0
15 verbose cwd C:\Users\Braunson\Documents\GitHub\google-address-autocomplete
16 verbose Windows_NT 10.0.15063
17 verbose argv "F:\\Program Files\\nodejs\\node.exe" "F:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v7.5.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error google-address-autocomplete@1.2.0 build: `./node_modules/rollup/bin/rollup --config rollup.config.js`
22 error Exit status 1
23 error Failed at the google-address-autocomplete@1.2.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Braunson** [comment]
Really all I want to do is pass in the `result` object from Google into a second parameter in the callback.

**Comment by dericcain** [comment]
It looks like you are using Windows in which case when you run `build`, the command uses a relative path like `./node_modules/...`. I am thinking that Windows does not know how to handle the `.` (which means current directory in *nix systems). Try and update the `package.json` to this:

https://gist.github.com/dericgw/2cbe049b75dad9dd1d7297aece9516a9/revisions#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L30

**Comment by dericcain** [comment]
@Braunson If you are talking about essentially overwriting the existing formatted address, that would not be a great idea because that would introduce breaking changes. All we want to do here is **add** data to the result and not change the data.

**Comment by Braunson** [comment]
@dericgw I was going to return a second item in the callback that would return the full Google `result` response. I'm not touching the first callback parameter `formatted_address`.

**Comment by dericcain** [comment]
Okay, so something like `rawResult`? I think that will be fine. That way if someone just wants the address, they have easy access to it but if they need the other things, then they can access the `rawResult` as the second param of the callback. I like it.

**Comment by Braunson** [comment]
Ok a PR is in.

I have another question to see if you have any ideas. I'm also looking to apply this to any element with a certain data attribute like `[data-google-autocomplete]`

Now I have a few options:

1. Create a jQuery wrapper that uses this plugin and creates the separate instances for each element with that attribute.
2. Use `document.querySelectorAll('[data-foo]');` somehow in the plugin

Any other ideas?

**Comment by dericcain** [comment]
Cool, I'll check out the PR tonight when I get home.

To solve your other issue, you could possibly use a `forEach` or just a `for` loop to achieve what you want to do.
```JavaScript
const els = document.querySelectorAll('[data-foo="true"]');
els.forEach((el, index) => {
  const newClass = 'somethingrandom' + index;
  el.classList.add(newClass);
  new AddressAutocomplete(`.${newClass}`, result => console.log(result));
});
```
Here is a codepen: https://codepen.io/dcain19/pen/BJarjK

It isn't very pretty and could def be made more performant. I think what we would want to do longterm is add a conditional to the constructor that looks to see if there are multiple elements or just one element and handle them accordingly.

**Comment by ghost** [comment]
@Braunson Made a few notes on the PR. Overall, it looks great and I really appreciate the help. I think returning the raw results will make the lib a lot more flexible.

**Comment by Braunson** [comment]
@dericcain I don't see the notes?

**Comment by ghost** [comment]
@Braunson My apologies, I forgot to complete the review. Let me know if you have any questions or need help with anything!
